config/routes.rb
Rails.application.routes.draw do
get "search", to: "blogs#search"
  devise_for :users
  resources :blogs do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  root "blogs#index"
  
  get "commentshow" ,to: "comments#show" 
  get "my_blog", to: "blogs#my_blog"
  post "like" , to: "blogs#like"
  get "like" , to: "blogs#like"
  post "anilc", to: "comments#collapse"
  get "mylike", to: "blogs#mylike"
  get "/", to: "blogs#index"
  # delete "commentshow" , to: "comments#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    
    validates :author, :authors_email, :title, :desciption, :pages, :release_date, presence: true
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    



    
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true
  belongs_to :blog
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user! , except: [:index]
#  if current_user.id ==  user_id 
#   before_action [:edit]
#  end
  before_action :set_blog, only: %i[ show edit update destroy ]
 

  # def d_down
  #   @blog = Blog.order(:title)
  #   puts "action dropdown"
  #   redirect_to root_path
  # end

  # GET /blogs or /blogs.json

  def first
  end

  def index
   
    if params[:filter].nil? || params[:filter] == "nil"
      @blog = Blog.all
    else
      @blog = Blog.where(category: params[:filter])    
    end
    @a = User.all

  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @ul = Like.find_by(blog_id: params[:id], user_id: current_user.id)
    @total_likes = Like.where(ref_id: 1, blog_id: params[:id]) 
  end


  # GET /blogs/new
  def new  
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.title = @blog.title.capitalize
    @blog.author = @blog.author.capitalize

      if @blog.save
          redirect_to blogs_path, notice: "new voter has been added successfully"
      else
          render :new ,status: :unprocessable_entity
      end 
  end



  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    if user_signed_in?
      if @blog.update(blog_params)
        redirect_to my_blog_path , notice: "new voter has been edited successfully"
      else 
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to root_path
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
      redirect_to my_blog_path
  end

def id_pass
  @users = User.all

end 


def search
  if params[:query].strip != ""
    @blog = Blog.where("blogs.title LIKE ?","%" + params[:query] + "%").order(title: :desc)
 

  else
    @blog=[]
  end
end
 
def my_blog
  @blog = Blog.where(user_id: current_user.id )
end

def like

    @a = current_user.id
    @b = Blog.find(params[:param1])
    
    @like = Like.find_by(user_id: @a , blog_id: @b.id)

    if @like.class == NilClass
      Like.create(user_id: @a , blog_id: @b.id, ref_id: 1)
    elsif @like.ref_id == 1
      @like.update(ref_id: 0)
    else
      @like.update(ref_id: 1)
    end
    redirect_to blog_path(@b.id)
    
end

def mylike
  @my =   Like.select(:blog_id).where(user_id: current_user.id ,ref_id: 1)
 
 
  @mylike = Blog.where(id: @my)
 


 
  # @mylike = Blog.where(params[:bl] )
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:author, :authors_email, :title, :desciption, :pages, :release_date, :user_id, :category )
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @blog = Blog.find(params[:blog_id])
        @comment = @blog.comments.create(params[:comment].permit(:body, :user_id))
        if @comment.save
            redirect_to commentshow_path(@blog.id ), notice: "comment added successfully"
        else
            redirect_to blog_path(@blog.id) , notice: "you can't submit empty comment"
        end 
    end

    def show
        @blog = Blog.find(params[:blog_id])                     
    end
    
    def collapse
        @obj = Comment.find(params[:param1])
        @obj.destroy
        redirect_to commentshow_path(blog_id: params[:param1])
        
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Author:</strong>
    <%= blog.author %>
  </p>

  <p>
    <strong>Authors email:</strong>
    <%= blog.authors_email %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= blog.title %>
  </p>

  <p>
    <strong>Desciption:</strong>
    <%= blog.desciption %>
  </p>

  <p>
    <strong>Pages:</strong>
    <%= blog.pages %>
  </p>

  <p>
    <strong>Release date:</strong>
    <%= blog.release_date %>
  </p>

</div>

app/views/blogs/_form.html.erb
<div class="maindiv">
<div class="maindiv2">
<%= form_with model: @blog do |form| %>
  <% if @blog.errors.any? %>
      <% @blog.errors.full_messages.each do |message|%>
         <p style="color: red;"><%= message %><p>
      <% end %>
  <% end  %>

 
  <br>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select(:category, options_for_select([["Sports","Sports"],["Tech", "Tech"],["Movies", "Movies"],["Medical","Medical"]])) %>
  </div>
  <br>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :authors_email, style: "display: block" %>
    <%= form.email_field :authors_email %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :desciption, style: "display: block" %>
    <%= form.text_area :desciption %>
  </div>

  <div>
    <%= form.label :pages, style: "display: block" %>
    <%= form.number_field :pages %>
  </div>

  <div>
    <%= form.label :release_date, style: "display: block" %>
    <%= form.date_field :release_date %>
  </div>

   <div>
    <% form.label :user_id, id: :user_id , type: :hidden %>
    <% current_user.id %>
    <input value="<%= current_user.id%>" name="blog[user_id]" style="display:none">
  </div>

<br>
  <div>
    <button><%= form.submit %></button>
  </div>
<% end %>
</div>

</div>

app/views/blogs/_home.html.erb
<div class="for_home">
    <%= button_to "Add New Blog" , new_blog_path, method: :get  %>
    <form class="d-flex" action="/search" >
        <input class="form-control me-2" style="border-bottom:2px solid black" type="search" name="query" placeholder="Search here...." aria-label="Search" >
        <button class="btn btn-outline-success" type="submit" style="height:20px">Search</button>
    </form>
    <%= button_to "My Blog" , my_blog_path, method: :get  %>
    <%= button_to "Liked Blogs" , mylike_path, method: :get  %>
    <%= button_to "Edit profile", edit_user_registration_path, method: :get %>
    <%= button_to "Log out", destroy_user_session_path, method: :delete %>

    <%# <button class="addnewblock"><%= link_to "My Blog" , new_blog_path  %>    
</div>


<%= notice %>
<br>            
<br>
<h1 style=" text-align:center; margin-top:100px;" >Listing all Blogs</h1>

<form method="get" action="">
    <select name="filter" style="background-color: transparent;">
        <option value="nil">all</option>
        <option value="Sports">Sports</option>
        <option value="Tech">Tech</option>
        <option value="Movies">Movies</option>
        <option value="Medical">Medical</option>

    </select>
    <button type="submit">submit</button>
</form>

<br>
<br>
<table border="3">
    <thead>
        <th>Author Name</th>
        <th>Blog Title</th>
        <th>Category</th>
        <th colspan="3" >Action</th>

    </thead>
    <tbody>
        <% @blog.each do |a|%>
        <tr class="row">
            <td><%= a.author %></td>
            <td><%= a.title %></td>
            <td><%= a.category %></td>
            <td><%= link_to "Show more" , a %></td>
            

        </tr>
        <%end%>
    </tbody>
</table>
 

app/views/blogs/edit.html.erb
<div class="for_home">
    <%= button_to "Add New Blog" , new_blog_path, method: :get  %>
    <%= button_to "Home" , root_path, method: :get %>
    <%= button_to "Log out", destroy_user_session_path, method: :delete %>
</div>
<h1 style="margin-top:100px;">Edit blog here</h1>

<%= render "form" %>

app/views/blogs/first.html.erb
<% if user_signed_in? %>
    <h1>Welcome</h1>
    <br>
    <%= link_to "click here to view all blogs" , blogs_path %>
    <br>
    <%= button_to "Log out", destroy_user_session_path, method: :delete %>
<% else %>
    <%= button_to "login" , new_user_session_path  %>
    <%= render new_user_session_path %>
        
<% end %>

app/views/blogs/index.html.erb
    <% if user_signed_in? %>
        <%= render "home"%>
    <% else %>
    <div style="height:60% ;width:100%; background-image:url(https://thumbs.dreamstime.com/z/blog-woodn-dice-depicting-letters-stack-newspapers-leaning-dice-34801080.jpg?w=1200);background-position:center; background-size:cover;">
        <div style="margin-left:40px">
            <h1 style="margin:30px 0px 40px 50px">Please Log-in or Sign-up to continue...</h1>
            <div id="index-but">
                <h1 style="margin:40px 0px 40px 50px;"> <%= button_to "Log in" , new_user_session_path  %></h1>  
                <h1 style="margin-bottom:450px; margin-left:50px;"> <%= button_to "Sign up" , new_user_registration_path ,method: :get %></h1>
            </div>
        </div>
    </div> 
    <% end %>

  

app/views/blogs/my_blog.html.erb
<div class="for_home">
    <%= button_to "Add New Blog" , new_blog_path, method: :get  %>
    <form class="d-flex" action="/search" >
        <input class="form-control me-2" style="border-bottom:2px solid black" type="search" name="query" placeholder="Search here...." aria-label="Search" >
        <button class="btn btn-outline-success" type="submit" style="height:20px">Search</button>
    </form>
    <%= button_to "Home" , root_path , method: :get %>
     <%= button_to "Edit profile", edit_user_registration_path, method: :get %>
    <%= button_to "Log out", destroy_user_session_path, method: :delete %>
    <%# <button class="addnewblock"><%= link_to "My Blog" , new_blog_path  %>
 
    
</div>

<% if @blog.size==0 %>
    <h1 style="width:500px; margin-top:100px;"><i><marquee behavior="alternate" >You have no  blogs</marquee></i></h1>
<% else %>
    <h1 style="margin-top:100px; margin-bottom:50px;">My Blogs</h1>


    <table border="3">
        <thead>
            <th>Author Name</th>
            <th>Email</th>
            <th>Blog Title</th>
            <th colspan="3" >Action</th>

        </thead>
        <tbody>
            <% @blog.each do |a|%>
            <tr class="row">
                <td><%= a.author %></td>
                <td><%= a.authors_email %></td>
                <td><%= a.title %></td>
                    <td><%= link_to "view" , a %></td>
                    <td><%= link_to "edit" , edit_blog_path(a)%></td>
                    <td><%= button_to "delete" , a , method: :delete, data: {
                        turbo_confirm: "Are You Sure?" } %></td>


            </tr>
            <%end%>
        </tbody>
    </table>
<% end %>

app/views/blogs/mylike.html.erb
<div class="for_home">
    <%= button_to "Add New Blog" , new_blog_path , method: :get  %>
    <%= button_to "Home" , root_path , method: :get %>
    <%= button_to "Log out", destroy_user_session_path, method: :delete %>
</div>

<h1 style="margin-top:100px; margin-bottom:30px;" ><strong>My Liked Blogs</strong></h1>

<% @mylike.each do|i| %>
 <a style="margin-bottom:10px; font-size:20px;" href="blogs/<%= i.id%>"><%= i.title%></a>
<% end %>

app/views/blogs/new.html.erb
<div class="for_home" >
    <%= button_to "Add New Blog" , new_blog_path , method: :get %>
    <%= button_to "Home" , root_path , method: :get %></button>
    <%= button_to "Log out", destroy_user_session_path, method: :delete %>
</div>
<h1 style="margin-top:100px;">New blog</h1>

<%= render "form" %>

app/views/blogs/search.html.erb
<div class="for_home">
    <%= button_to "Add New Blog" , new_blog_path, method: :get  %>
    <form class="d-flex" action="/search" >
        <input class="form-control me-2" style="border-bottom:2px solid black" type="search" name="query" placeholder="Search here...." aria-label="Search" >
        <button class="btn btn-outline-success" type="submit" style="height:20px">Search</button>
    </form>
    <%= button_to "Home" , root_path, method: :get %>
    <%= button_to "Log out", destroy_user_session_path, method: :delete %>
</div>
<h1 style="margin:100px 0px 50px 0;"><u>Search Results</u></h1>
<% @blog.each do |i| %>
 <a style="margin-bottom:10px; font-size:20px;" href="blogs/<%= i.id%>"><%= i.title%></a>
<% end %>

<% if @blog.size==0 %>
    <h1 style="width:500px; margin-top:100px;"><i><marquee behavior="alternate" >no blogs available</marquee></i></h1>
<% end %>

app/views/blogs/show.html.erb
<div class="for_home">
    <%= button_to "Add New Blog" , new_blog_path , method: :get  %>
    <%= button_to "Home" , root_path , method: :get %>
    <%= button_to "Edit profile", edit_user_registration_path, method: :get %>
    <%= button_to "Log out", destroy_user_session_path, method: :delete %>
</div>
<h1 style="margin-top:100px;"><strong>Showing Blog Details</strong></h1>

<div class="showdiv">
    <h3>Author's Name:  <em><%= @blog.author %></em></h3>
    <br>
    <h3>Authors Email:  <em><%= @blog.authors_email %></em></h3>
    <br>
    <h3>Blog Title: <em><%= @blog.title %></em></h3>
    <br>
    <h3>Blog Description: <em><%= @blog.desciption %></em></h3>
    <br>
    <h3>Pages: <em><%= @blog.pages %></em></h3>
    <br>
    <h3>Blog Release Date: <em><%= @blog.release_date %></em></h3>
    <br>
    <form method="post" action="/like"><input value="<%= @blog.id%>" name="param1" style="display:none;">
    <form method="post" action="/mylike"><input value="<%= @blog.id%>" name="param1" style="display:none;">
    <% if @ul %>
        <% if @ul.ref_id == 0 %>
            <% a= "Like" %>
        <% else %>
            <% a = "Unlike" %>
        <% end %>
            <button type="submit"><%= a %></button></form> <%= @total_likes.size %>
            
    <% else %>
        <button type="submit">Like</button></form> 
        <%= @total_likes.size %>

    <% end %>
    <%= (@total_likes.size <= 1)? "Like" : "Likes"  %> 
    <br>
    <button class="addnewblock"><%=link_to "show comments" , commentshow_path(blog_id:@blog.id) %></button>
        
    <br>
   
</div>
        




       

app/views/comments/_comment.html.erb
<div style="hieght:20px; min-width:40%; text-align:center; display:flex; justify-content:space-between; flex-wrap:wrap; ">
<div style="" ><h4><%= comment.body %><h4></div>
<br>
<br>
<p><%= time_ago_in_words(comment.created_at) %> ago<p>


    <%=button_to "delete" , [comment.blog,comment], method: :delete, data:{turbo_confirm: "are you sure"} %>
</div>

app/views/comments/_form.html.erb
<%= form_for ([@blog,@blog.comments.build]) do |f| %>
    <p>
       <%= f.label :body %> 
       <%= f.text_field :body %>
    </p><br>
    <%= f.number_field :user_id, value: current_user.id, type: :hidden%>
    <p>
       <pre><button><%= f.submit %></button>                       </pre>
    </p>
<% end %>

app/views/comments/show.html.erb
<div class="for_home" >
   
    <%= button_to "Add New Blog" , new_blog_path , method: :get  %>
    <%= button_to "Home" , root_path , method: :get %>
    <%= button_to "Log out", destroy_user_session_path, method: :delete %>
</div><br>
<br>
<br>
<h2 style="margin-top:50px; margin-bottom:20px;"><u><%= @blog.comments.count %> Comments </u></h2>
    


<div style="width: 600px; padding: 10px; align-items:center; display:flex;" >
    <table style="width: 700px; padding: 50px; overflow-y:scroll" >
    
    <%allcomm = Comment.where(blog_id: params[:blog_id]) %>
    <% allcomm.each do |x| %>
    
        <tr>
            <% if x.user_id == current_user.id %>
                <form method="post" action="/anilc">
                    <input value="<%= x.id %>" name="param1" style="display:none;">
                    <td><%= x.body %></td>         
                    <td><%= time_ago_in_words(x.created_at) %> ago </td>             
                    <td><button type="submit">delete</button></td>
                </form> 
            <% else %>
                    <td><%= x.body %></td>         
                    <td><%= time_ago_in_words(x.created_at) %> ago </td>             
             
            <% end %>
        </tr>

    <% end %>
    </table>
</div>


<div style="margin-top:10px;">
    <h3>Add comments: </h3>
    <%= render "comments/form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Page</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
      *{
        padding:0;
        margin:0;
        box-sizing:border-box;
       
        
      }

      html{
        @import url('https://fonts.googleapis.com/css2?family=Ysabeau+SC:wght@500&display=swap');
        font-family: 'Ysabeau SC', sans-serif;

      }

      em{
        background-color: rgb(146, 187, 228);
      }

      a {
        text-decoration: none;
      }

      body{
        min-height:110vh;
        width: 100%;
        background-image:url(https://images.pexels.com/photos/235985/pexels-photo-235985.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500) ;
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover;
        
      } 

      /* a:visited{
        color:brown;
      }
      a:link{
        color: green;
      }
      a:active{
        color: rgb(1, 26, 1)
      }
      a:hover{
        color: rgb(233, 164, 17);
        font-size: 20px;
     
      } */
      button{
        background-color: transparent;
      }

      table{
        height: 50vh;
        width: 70%;
        align-content: center;
        box-shadow: 0 0 30px black;
      }

      .row{
        text-align: center;
      }

      #div{
        height: auto;
        width: auto;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-wrap: wrap;
        flex-direction: column;
      }

      .maindiv{
        height: 50vh;
        width: 100%;
        display: flex;
        justify-content: space-between;
        align-items: center;
        flex-direction: column;
      }

      .maindiv2{
        height:auto ;
        min-width: 30%;
        display: flex;
        justify-content: space-between;
        align-items: center;
        flex-direction: column;
        box-shadow: 0 0 30px rgb(46, 46, 46);
        border-radius: 16px;
        margin-bottom: 30px;
        margin-top: 30px;
        padding: 20px ;
      }

      input{
        border: none;
        border-bottom: 2px solid brown;
        background-color: transparent;
      }

      input:focus{
        outline: none;
      }

      .for_home{
        height: 10vh;
        width: 100%;
        display:flex;
        justify-content:space-around;
        background-image:url(https://images.pexels.com/photos/235985/pexels-photo-235985.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500) ;
        background-size: 100%;
        align-items: center;
        box-shadow: 0 0 70px rgb(2, 2, 2);
        position: fixed;
        top:0px ;
      }

      

      .for_home button{
        height:40px; 
        width:auto; 
        padding-left: 20px;
        padding-right: 20px;
        border-radius:20px;
        font-size: 15px;
        font-weight:bolder;
      }


      #index-but button{
        height:40px; 
        width:100px; 
        border-radius:20px;
        font-size: 20px;
      }

      .btn{
        margin-bottom: 10px;
      }
      
      .showdiv{
        box-shadow: 0 0 30px rgb(30, 29, 29);
        margin-top: 50px;
        margin-bottom: 60px;
        border-radius:10px;
        padding: 20px ;
        min-height: fit-content;
        min-width: fit-content;
      }

      .login_button{
        margin-top:100px;
        display: flex;
        flex-direction: row;
        justify-content: space-around;
      }

      ::placeholder{
        color: black;
        font-size: 15px;
      }

      .addnewblock a{
        color: black;
      }

      .field>input{
        background-color: transparent;
      }

    </style>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div id="div">
      
      <%= yield %>
      <br>

    </div>
    
  </body>
</html>